**Шийдвэрийн мод**

Энэ нь хамгийн энгийн бөгөөд түгээмэл ашиглагддаг алгоритм юм. Шийдвэрийн мод гэдэг нь дотоод зангилаа нь шинж чанарыг илэрхийлдэг, мөчир нь шийдвэрийн дүрмийг, навчны зангилаа бүр нь үр дүнг илэрхийлдэг урсгалын диаграммтай төстэй модны бүтэц юм. Шийдвэрийн модны хамгийн дээд цэгийг үндэс зангилаа гэдэг. Өгөгдлийн шинж чанарын аль нэг онцлох хэсгээр нь жижиг хэсгүүдэд буюу зангилаануудад хуваана. Энэ нь рекурсив байдлаар хуваана. Энэхүү урсгалтын диаграмтай төстэй бүтэц нь шийдвэр гаргахад тань тусалдаг 


In [ ]:
import pandas
import scipy
import numpy
from sklearn.preprocessing import MinMaxScaler

Өгөгдлийн хэмжээсийг өөрчлөх 

In [ ]:
df = pandas.read_csv('winequality-red.csv', sep=';')
array = df.values
# Separating data into input and output components
x = array[:,0:8]
y = array[:,8]
scaler = MinMaxScaler(feature_range = (0,1))
rescaledX = scaler.fit_transform(x)
numpy.set_printoptions(precision = 3) # Setting precision

print(rescaledX[0:5,:])

Өгөгдлийн стандартчлал

Өгөгдлийн стандарчлал нь янз бүрийн арга хэрэгсэл ба ялгаатай хазайлтын ялгаатай шинж чанаруудыг 0 - ийн дундаж ба 1 стандарт хазайлттай стандарт Гаусс тархалт болгон хувиргахад тусалдаг Scikit-learn-ийн standartScaler классын ашиглан өгөгдлийг стандарчилдаг

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(x)
rescaledX = scaler.transform(x)
rescaledX[0:5,:]

**2-тын дараалалд оруулах**

Энэ аргын хувьд босго хэмжээнээс дээш бүх утгыг 1 болгож, босготой тэнцүү ба түүнээс доош утгыг 0 болгоно. Энэ арга нь магадлал тооцоологдох үед өгөгдлийг тодорхой утга болгон хөрвүүлэхэд хэрэгтэй болно. Өгөгдлийг 2-т руу хөрвүүлэхдээ binarizer классыг ашиглан хийдэг.

In [ ]:
from sklearn.preprocessing import Binarizer
binarizer = Binarizer(threshold=0.0).fit(x)
binary_X = binarizer.transform(x)
binary_X[0:5,:]

**Энкодлох, кодчлол**

Категорийн өгөгдөлтэй харьцахдаа OneHotEncoder класс ашиглан кодчилол хийдэг

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
print(encoder.fit([[0,1,6,2],[1,5,3,5],[2,4,2,7],[1,0,4,2]]))
encoder.transform([[2,4,3,4]]).toarray()

**Шошгоны кодчилол**

Шошго нь үг эсвэл тоо байж болно. Ихэнхдээ сургалтын өгөдлийг унших боломжтой болгох үүднээс үгээр тэмдэглэдэг. Шошгоны кодчилол нь үгийн тэмдэглэгээг тоогоор хөрвүүлж алгоритм дээр ажиллах боломжийг олгоно.

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
input_classes = ['A','B','C','D','E']
label_encoder.fit(input_classes)
for i, item in enumerate(label_encoder.classes_):
  print(item,'-->', i)
input_classes = ['A','B','C','D','E']
labels=['B','C','D']
label_encoder.transform(labels)
label_encoder.inverse_transform(label_encoder.transform(labels))

A --> 0
B --> 1
C --> 2
D --> 3
E --> 4


array(['B', 'C', 'D'], dtype='<U1')

#SVM аргаар хөхний хавдрыг урьдчилан таамаглах

Өвчтний эмчилгээний түүх, эрүүл мэндийн мэдээллийг ашиглан хөхний хорт хавдрын тохиолдлыг урьдчилан таамаглахын тулд машин сургалтын Тулгуур вектор машины аргыг ашиглана. Хөхний хорт хавдар Висконсин (Оношлогоо) Датасетийг ашиглая. Дараах алхмуудаар хэрэгжүүлнэ.

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(
    {
        "Radius_mean" : [17.99, 20.57, 19.69, 11.42, 20.29, 12.42, 18.25, 13.71, 13, 12.46, 16.02, 15.78, 14.61, 12.76, 11.54, 8.597, 12.49, 12.18, 18.22, 9.042],
        "Texture_mean" : [10.38, 17.77, 21.25, 20.38, 14.34, 15.7, 19.98, 20.83, 21.82, 24.04, 23.24, 17.89, 15.69, 13.37, 10.72, 18.6, 16.85, 14.08, 18.87, 18.9],
        "Perimeter_mean": [122.8, 132.9, 130, 77.58, 135.1, 82.57, 119.6, 90.2, 87.5, 83.97, 102.7, 103.6, 92.68, 82.29, 73.73, 54.09, 79.19, 77.25, 118.7, 60.07],
        "Area_mean": [1001, 1326, 1203, 386.1, 1297, 477.1, 1040, 577.9, 519.8, 475.9, 797.8, 781, 664.9, 504.1, 409.1, 221.2, 481.6, 461.4, 1027, 244.5],
        "Diagnosis" : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0] 
    }
)

In [ ]:
df.to_csv('cancer_data.csv')
print(df.shape)
print(df)

(20, 5)
    Radius_mean  Texture_mean  Perimeter_mean  Area_mean  Diagnosis
0        17.990         10.38          122.80     1001.0          1
1        20.570         17.77          132.90     1326.0          1
2        19.690         21.25          130.00     1203.0          1
3        11.420         20.38           77.58      386.1          1
4        20.290         14.34          135.10     1297.0          1
5        12.420         15.70           82.57      477.1          1
6        18.250         19.98          119.60     1040.0          1
7        13.710         20.83           90.20      577.9          1
8        13.000         21.82           87.50      519.8          1
9        12.460         24.04           83.97      475.9          1
10       16.020         23.24          102.70      797.8          1
11       15.780         17.89          103.60      781.0          1
12       14.610         15.69           92.68      664.9          0
13       12.760         13.37           

Алхам 2. Онцлог шинж чанар, зорилтыг тодорхойлно

In [ ]:
X = df.drop('Diagnosis', axis =1)
y = df['Diagnosis']
print(y)

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    0
13    0
14    0
15    0
16    0
17    0
18    1
19    0
Name: Diagnosis, dtype: int64


Алхам 3. SVM алгоритмын загварын бүтээхэд sklearn сан ашиглан өмнө өгөгдлийг сургалтын болон туршилтын гэж 2 хуваана.

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

Алхам 4. SVM алгоритмын загварыг бүтээхэд sklearn сан ашиглан өмнө өгөгдлийг сургалтын болон туршилтын гэж 2 хуваана.

Sklearn SVM модулаас SVC функцыг оруулж ирж тулгуур вектор машины загварыг бүтээнэ. Хэрэгжүүлэх цөм нь kernel буюу шугамани ангилагч байна.

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(kernel='linear')

Алхам 5. SVM алгоритмын загварыг ашиглан утгыг урьдчилан таамаглах

In [ ]:
y_pred = svclassifier.predict(X_test)

Алхам 6. SVM моделийг үнэлэх

In [ ]:
from sklearn.metrics import classification_report 
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[1 0]
 [1 2]]
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.67      0.80         3

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4



Мөн SVM нь олон гишүүнт цөмтэй байж болно. SVC функцыг оруулж ирээд цөмийг нь 'poly' гэж тохируулна.

In [ ]:
from sklearn.svm import SVC
svclassifier_poly = SVC(kernel = 'poly', degree = 8)
svclassifier_poly.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

Үр дүн

Сургасан SVM моделиор таамаглал хийж үзээд моделийн үнэлгээг гаргана.

In [ ]:
y_pred_poly = svclassifier_poly.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_poly))
print(classification_report(y_test, y_pred_poly))

[[1 0]
 [2 1]]
              precision    recall  f1-score   support

           0       0.33      1.00      0.50         1
           1       1.00      0.33      0.50         3

    accuracy                           0.50         4
   macro avg       0.67      0.67      0.50         4
weighted avg       0.83      0.50      0.50         4



Мөн SVM нь Гауссын цөмтэй байж болно. SVC функцыг оруулж ирээд цөмийг нь 'rbf' гэж тохируулна.

In [ ]:
from sklearn.svm import SVC
SVCsvclassifier_gaus = SVC(kernel='rbf')
SVCsvclassifier_gaus.fit(X_train, y_train)

SVC()

Сургасан SVM моделиор таамаглал хийж үзээд моделийн үнэлгээг гаргана.

In [ ]:
y_pred_gaus = svclassifier_poly.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_gaus))
print(classification_report(y_test, y_pred_gaus))

[[1 0]
 [2 1]]
              precision    recall  f1-score   support

           0       0.33      1.00      0.50         1
           1       1.00      0.33      0.50         3

    accuracy                           0.50         4
   macro avg       0.67      0.67      0.50         4
weighted avg       0.83      0.50      0.50         4



Мөн SVM нь 'sigmoid' цөмтэй байж болно. SVC функцыг оруулж ирээд цөмийг нь 'sigmoid' гэж тохируулна.

In [ ]:
from sklearn.svm import SVC
svclassifier_sigmoid = SVC(kernel = 'sigmoid')
svclassifier_sigmoid.fit(X_train, y_train)
y_pred_sigmoid = svclassifier_poly.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred_sigmoid))
print(classification_report(y_test, y_pred_sigmoid))

[[1 0]
 [2 1]]
              precision    recall  f1-score   support

           0       0.33      1.00      0.50         1
           1       1.00      0.33      0.50         3

    accuracy                           0.50         4
   macro avg       0.67      0.67      0.50         4
weighted avg       0.83      0.50      0.50         4

